routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('posts/','PostController@index');
Route::get('posts/create','PostController@create');
//Route::get('posts/{id}','PostController@destroy');

//return yajra index view
Route::get('posts/yajra','PostController@index2');
//return all posts with users
Route::get('getposts','PostController@getPosts')->name('posts.list');
Route::get('posts/delete','PostController@delete')->name('posts.delete');

Route::resource('mahendra','Mahendra');
Route::get('users','Mahendra@getUsers')->name('users.list');

Route::get('hasone','OneController@index');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    //
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['user_id','title'];

    public function user(){
    	return $this->belongsTo(User::class);
    }
}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
}

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $fillable = ['name'];


    public function user(){
    	return $this->belongsToMany(User::class, 'role_user');
    }
}

app/Supplier.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    public function orders()
    {
        return $this->hasOneThrough(
            Order::class,
            Product::class,
            'supplier_id', // Foreign key on products table...
            'product_id', // Foreign key on orders table...
            'id', // Local key on suppliers table...
            'id' // Local key on products table...
        );
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function posts(){

        return $this->hasMany(Post::class);
    }
    public function roles(){
        return $this->belongsToMany(Role::class, 'role_user');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Mahendra.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Role;
use App\User;
use DataTables;
class Mahendra extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       
        return view('mahendra.index');
    }
    public function getUsers(Request $request){
        if ($request->ajax()) {
            // $data = Post::with('user')->get();
            $data = User::with('roles')->get();
            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function($row){
                    $editUrl = '/mahendra/'.encrypt($row->id).'/edit';
                    $actionBtn = "<a href=".$editUrl." class='edit btn btn-success btn-sm'>Edit</a>";
                    return $actionBtn;
                })
                ->addColumn('role',function($row){
                    $r = [];
                    foreach($row->roles as $role){
                        array_push($r,$role->name);
                    }
                    return $r;
                })
                ->rawColumns(['action','role'])
                ->make(true);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         $roles = Role::all();
        return view('mahendra.form',compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $u = User::create(['name'=>$request->username,'email'=>$request->email]);        
       $user = User::find($u->id);   
       $roleIds = $request->role;
       $user->roles()->attach($roleIds);
       return redirect('mahendra');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $id = decrypt($id);
        $user = User::find($id);
        // $r = [];
        // foreach($user->roles as $role){
        //     array_push($r,$role->name);
        // }
        // $user = [$user];
        // return $user;
        $roles = Role::all();
        return view('mahendra._form',compact('user','roles'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $id = decrypt($id);
        $data = ['name'=>$request->username,'email'=>$request->email];
        $u = User::find($id)->update($data);
        $user = User::find($id);
        $roleIds = $request->role;
        //$user->roles()->detach($roleIds);
        $user->roles()->sync($roleIds);
        return redirect('mahendra');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/OneController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Supplier;
use App\Order;
class OneController extends Controller
{
    public function index(){
        $suppliers = Supplier::find(1);	
        $supplier_one = $suppliers->orders;
        //dd($supplier_one);

        $suppliers = Supplier::find(2);	
        $supplier_two = $suppliers->orders;

        return view('welcome',compact('supplier_one','supplier_two'));
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Post;
use DataTables;
class PostController extends Controller
{
	public function index(){
		$posts = Post::with('user')->get();
		return view('posts.index',compact('posts'));
	}
    public function create(){
    	$user = User::find(4);

    	$post = new Post();
    	$post->title = "Hello Worl";
    	$user->posts()->saveMany([$post]);
    }
    public function destroy($id){
    	Post::find($id)->delete();
    	return back();
    }
    public function index2(){
    	return view('posts.yajra');
    }
    public function getPosts(Request $request){
    	if ($request->ajax()) {
            $data = Post::with('user')->get();
            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function($row){
                    $actionBtn = '<a href='"{{ url('mahendra/edit') }}"' class="edit btn btn-success btn-sm">Edit</a> 
                    <a href="{{  }}" class="delete-btn btn btn-danger btn-sm">Delete</a>';
                    return $actionBtn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
    }
    public function delete($id){
    	return response()->json(['sucess','Delete'.$id]);
    }
}

resources/views/mahendra/_form.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel DataTables</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"/>
    <link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet">
</head>
<body>
<h2 class="text-center">Laravel 7|8 Yajra Datatables Example</h2>
<a href="{{ url('mahendra/create') }}" class="nav-link bg-light text-right">{{ Request::is('mahendra/create') ? 'Home/Mahendra/Add New' : '' }}</a>    
<div class="container">
    <form method="post" action="{{ route('mahendra.update',[encrypt($user->id)]) }}" enctype="multipart-form/data">
        @method('PUT')
    	@csrf()
    <div class="form-group">
    	<label>Username</label>
    	<input type="text" name="username" class="form-control" placeholder="Username" id="username" value="{{ $user->name}}">
    </div>
    <div class="form-group">
    	<label>E-Mail</label>
    	<input type="text" name="email" class="form-control" placeholder="E-Mail" id="email" value="{{ $user->email }}">
    </div>
    <div class="form-group">
    	<label>Select Roles</label>
    	<div class="row">
            @php $arrayRoles = $user->roles->pluck('id') @endphp
    		@foreach($roles as $role)
    		<div class="col-sm-3">
    			<input type="checkbox" {{ in_array($role->id,$arrayRoles->toArray()) ? 'checked' : '' }} name="role[]" value="{{ $role->id }}" class="custome-control"> {{ $role->name }}
    		</div>
    		@endforeach
    	</div>
    </div>
    <div class="form-group">
    	<input type="reset" class="btn btn-danger" value="Cancel">
    	<input type="submit" class="btn btn-success" value="Create">
    </div>	
    </form>
</div>
   
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>  
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>

<script type="text/javascript">
 

</script>
</html>

resources/views/mahendra/form.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel DataTables</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"/>
    <link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet">
</head>
<body>
<h2 class="text-center">Laravel 7|8 Yajra Datatables Example</h2>
<a href="{{ url('mahendra/create') }}" class="nav-link bg-light text-right">{{ Request::is('mahendra/create') ? 'Home/Mahendra/Add New' : '' }}</a>    
<div class="container">
    <form method="post" action="{{ route('mahendra.store') }}" enctype="multipart-form/data">
    	@csrf()
    <div class="form-group">
    	<label>Username</label>
    	<input type="text" name="username" class="form-control" placeholder="Username" id="username">
    </div>
    <div class="form-group">
    	<label>E-Mail</label>
    	<input type="text" name="email" class="form-control" placeholder="E-Mail" id="email">
    </div>
    <div class="form-group">
    	<label>Select Roles</label>
    	<div class="row">
    		@foreach($roles as $role)
    		<div class="col-sm-3">
    			<input type="checkbox" name="role[]" value="{{ $role->id }}" class="custome-control"> {{ $role->name }}
    		</div>
    		@endforeach
    	</div>
    </div>
    <div class="form-group">
    	<input type="reset" class="btn btn-danger" value="Cancel">
    	<input type="submit" class="btn btn-success" value="Create">
    </div>	
    </form>
</div>
   
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>  
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>

<script type="text/javascript">
 

</script>
</html>

resources/views/mahendra/index.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel DataTables</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"/>
    <link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet">
</head>
<body>
     <h2 class="text-center">Laravel 7|8 Yajra Datatables Example</h2>
    <a href="{{ url('mahendra/create') }}" class="btn btn-primary float-right">New Add</a>
<div class="container">
   
     <table class="table table-bordered datatable text-center">
        <thead>
            <tr>
                <th>No</th>
                <th>Name</th>
                <th>E-Mail</th>
                <th>Role</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
   
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>  
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>

<script type="text/javascript">
 $(function () {
    
    var table = $('.datatable').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('users.list') }}",
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex'},
            {data: 'name', name: 'name'},
            {data: 'email', name: 'email'},
            {data: 'role', name: 'role'},
            {
                data: 'action', 
                name: 'action', 
                orderable: true, 
                searchable: true
            },
        ]
    });
});

</script>
</html>

resources/views/posts/index.blade.php
<table border="1">
	<tr>
		<th>Id</th>
		<th>Author</th>
		<th>Title</th>
		<th>Create At</th>
		<th>Action</th>
	</tr>
	@foreach($posts as $post)
	<tr>
		<td>{{$post->id}}</td>
		<td>{{$post->user['name']}}</td>
		<td>{{$post->title}}</td>
		<td>{{$post->created_at}}</td>
		<td><a href="{{ url('posts/'.$post->id) }}">Delete</a></td>
	</tr>
	@endforeach
</table>

resources/views/posts/yajra.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel 8|7 Datatables Tutorial</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"/>
    <link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet">
</head>
<body>
    
<div class="container mt-5">
    <h2 class="mb-4">Laravel 7|8 Yajra Datatables Example</h2>
    <table class="table table-bordered yajra-datatable">
        <thead>
            <tr>
                <th>No</th>
                <th>Title</th>
                <th>Author</th>
                <th>E-Mail</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
   
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>  
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>

<script type="text/javascript">
  $(function () {
    
    var table = $('.yajra-datatable').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('posts.list') }}",
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex'},
            {data: 'title', title: 'title'},
            {data: 'user.name', name: 'user.name'},
            {data: 'user.email', name: 'user.email'},
            {
                data: 'action', 
                name: 'action', 
                orderable: true, 
                searchable: true
            },
        ]
    });
    
  });
  
    $(document).ready(function(){
        $(document).on('click','.delete-btn',function(){
               alert('hello');     
        });
    })

</script>
</html>